### ISSUE TITLE
Ensure Monday is wday 0

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_DS3231#36]
Issue brought up on the forum here: https://forums.adafruit.com/viewtopic.php?f=60&t=182751

**Comment by tekktrik** [comment]
Looking into this, it seems as if the driver code is correct, but the example is wrong.  I can confirm this and submit a PR to update the example code.  Happy to modify the guide to match if that's possible through Github.

**Comment by tekktrik** [comment]
Datasheet for reference:  https://datasheets.maximintegrated.com/en/ds/DS3231.pdf

It looks like the time is being set correctly since the weekday number is user-defined and auto-increments.  The register library seems to be set up correctly here as well, setting Monday as 0 to the register's 1 for first weekday.

**Comment by tannewt** [comment]
A PR would be great. Some examples are automatically updated in Learn. If this one isn't, then let me know and I can fix it. Thanks!

**Comment by tekktrik** [comment]
Sounds great!  Hardware on the way to dot i's and cross t's, but I can submit the PR to correct the example. :)

**Comment by tekktrik** [comment]
Should be resolved by #39 !

**Comment by tannewt** [comment]
Thank you!
